spring:
  application:
    name: batch-worker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3312/batch
    username: root
    password: password
    demo:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3312/demo
      username: root
      password: password
  batch:
    jdbc:
      table-prefix: BATCH_
      initialize-schema: never
    job:
      enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ibm:
  mq:
    queue-manager: DEV_CRAZY
    application-name: BATCH_MASTER
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
#    path: /swagger-ui/index.html
